repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        name: check syntax [.py]

      - id: check-builtin-literals
        name: check literals [.py]

      - id: check-json
        name: check syntax [.json]

      - id: pretty-format-json
        name: format [.json]
        args: [ "--autofix", "--no-sort-keys" ]

      - id: check-toml
        name: check syntax [.toml]

      - id: check-yaml
        name: check syntax [.yaml]

      - id: trailing-whitespace
        name: trim trailing whitespace

      - id: end-of-file-fixer
        name: fix end of file

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.280
    hooks:
      - id: ruff
        name: check code [ruff]
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: local
    hooks:
      - id: mypy
        name: check types using [mypy]
        entry: mypy
        language: system
        files: ".py$"
        pass_filenames: false

default_language_version:
  python: python3.11

default_stages: [ "commit" ]

exclude: (Pipfile.lock)$
